### ISSUE TITLE
Erste Planung

### ISSUE THREAD

**Issue by CoresualEle** [CoresualEle/Fussballmanager#1]
Sooo, hier sind die Issues, ist wie ein Forum in dem man Ideen und Bugs postet

**Comment by CoresualEle** [comment]
Kommentiert bitte einmal hier drunter, damit wir die verlinkung auf die Profile haben

**Comment by TjarleN** [comment]
nice

**Comment by jared2s** [comment]
test

**Comment by Blumenkohler** [comment]
JAJAJJAJAJA
